### ISSUE TITLE
Support for QPU?

### ISSUE THREAD

**Issue by herr-d** [PennyLaneAI/pennylane-rigetti#89]
Hello,

it seems that you no longer support the ```forest.qpu``` device.
Is there another way to run on the rigetti hardware? There still seem to be some examples on the pennylane website that reference the ```forest.qpu``` device.

Best wishes,
Daniel

**Comment by josh146** [comment]
Hey @herr-d! Good catch; indeed, the PennyLane-Forest plugin no longer supports QPUs due to recent server-side changes with the Rigetti QCS. Are you currently a QCS user?

Instead, I recommend accessing the Rigetti device via the [Amazon Braket](https://github.com/aws/amazon-braket-pennylane-plugin-python) plugin.

**Comment by herr-d** [comment]
Yes, I recently got access to QCS and wanted to try out running a few experiments through Pennylane. I don't know if I can use my QCS account with Braket though.

**Comment by josh146** [comment]
Thanks @herr-d! That is useful to know. I will explore and see if this is something we could offer support for again.

**Comment by kalzoo** [comment]
This is a _very_ old issue, but for the benefit of anyone else coming along - this does support QPU access now, direct to QCS!

What blocked us before was incompatibility between pyQuil v3.0 and `pennylane-forest`; now, along with the rename to `pennylane-rigetti` and thanks to @MarquessV and the PennyLane team, it works again on QPU and QVM.

**Comment by josh146** [comment]
@kalzoo shall we close this issue :)

**Comment by herr-d** [comment]
Yes, it has been a while. Lets close the issue :)...
